export const ADD_INGREDIENT='ADD_INGREDIENTS';
export const REMOVE_INGREDIENT='REMOVE_INGREDIENT';
export const SET_INGREDIENTS='SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED='FETCH_INGREDIENTS_FAILED'



export const PURCHASED_BURGER_SUCCESS='PURCHASED_BURGER_SUCCESS'
export const PURCHASED_BURGER_FAILED='PURCHASED_BURGER_FAILED'
export const PURCHASED_BURGER_START='PURCHASED_BURGER_START'
export const PURCHASED_INIT='PURCHASED_INIT'


export const FETCH_ORDER_SUCCESS ='FETCH_ORDER_SUCCESS'
export const FETCH_ORDER_FAILED='FETCH_ORDER_FAILED'
export const FETCH_ORDER_START='FETCH_ORDER_START'

export const AUTH_START='AUTH_START'
export const AUTH_SUCCESS='AUTH_SUCCESS'
export const AUTH_FAILED='AUTH_FAILED'
export const AUTH_LOGOUT='AUTH_LOGOUT'

export const SET_REDIRECT_PATH='SET_REDIRECT_PATH'
